before_script:
  - vault server -dev -dev-root-token-id="password" &
  - make install-deps

stages:
  - test
  - build

run-test:
  stage: test
  script:
    - make test-all

build:
  stage: build
  script:
    - make artifacts
  artifacts:
    paths:
      - vc
      - vault-client_1.1.2_amd64.deb
