before_script:
  - vault server -dev -dev-root-token-id="password" &
  - make install-deps

stages:
  - test
  - artifacts

run-test:
  stage: test
  script:
    - make test-all

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - vc
