before_script:
  - vault server -dev -dev-root-token-id="password" &
  - pyenv local 3.5.1
  - pip install -r docker/requirements.txt
  - make enable-settings SETTINGS=ci

stages:
  - test

run-test:
  stage: test
  script:
    - make test-all
