before_script:
  - vault server -dev -dev-root-token-id="password" &
  - sed -i 's/^token:.*/token: password/g' ~/.vaultrc
  - make install-deps


stages:
  - test
  - build

run-test:
  stage: test
  script:
    - cp sample/vaultrc ~/.vaultrc
    - chmod 0600 ~/.vaultrc
    - make test

build:
  stage: build
  script:
    - make artifacts
  artifacts:
    paths:
      - vc
      - vault-client_*_amd64.deb
