pkgbot:
  download-delay: 11
  repo: adsy-testing
  branches:
    - packaging
  stages: 
    - build
  packages:
    debian:
      jessie:
        - vault-client_*.deb
      wheezy: 
        - vault-client_*.deb
