pkgbot:
  download-delay: 11
  repo: adsy-testing
  branches:
    - packaging
  stages: 
    - package
  packages:
    debian:
      jessie:
        - build/apt-jessie-*deb
      wheezy: 
        - build/apt-wheezy-*deb
