language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

sudo: required

before_install:
  - export VAULT_VERSION=1.3.0
  - cp sample/vaultrc ~/.vaultrc
  - sed -i 's/^token:.*/token:\ password/g' ~/.vaultrc
  - chmod 700 ~/.vaultrc
  - wget -O - https://keybase.io/hashicorp/pgp_keys.asc | gpg --import
  - wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS.sig
  - wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS
  - gpg --verify vault_${VAULT_VERSION}_SHA256SUMS.sig vault_${VAULT_VERSION}_SHA256SUMS
  - bash -c "[[ \"$(sha256sum vault_${VAULT_VERSION}_linux_amd64.zip)\" == \"$(grep
    vault_${VAULT_VERSION}_linux_amd64 vault_${VAULT_VERSION}_SHA256SUMS)\" ]] || exit
    1"
  - sudo unzip vault_${VAULT_VERSION}_linux_amd64.zip -d /usr/local/bin

install:
  - pip install -r requirements.txt

before_script:
  - vault server -dev -dev-root-token-id="password" &
  - export VAULT_ADDR="http://127.0.0.1:8200"

script:
  - pytest --isort --black --flake8
